context:
  version: 1.1.2
  mojo_version: "=0.26.1"

package:
  name: mojo-asciichart
  version: ${{ version }}

source:
  git: https://github.com/DataBooth/mojo-asciichart.git
  tag: v1.1.2

build:
  number: 0
  script:
    - mkdir -p $PREFIX/lib/mojo/asciichart
    - cp -r src/asciichart/* $PREFIX/lib/mojo/asciichart/

requirements:
  build:
    - mojo-compiler ${{ mojo_version }}
  host:
    - mojo-compiler ${{ mojo_version }}
  run:
    # Mojo bytecode is not forwards-compatible across compiler minor versions,
    # so we require the exact compiler series used at build time.
    - mojo-compiler ${{ mojo_version }}

tests:
  - files:
      source:
        - test_package.mojo
    script:
      # Basic sanity checks: files installed under PREFIX
      - test -f $PREFIX/lib/mojo/asciichart/__init__.mojo
      - test -f $PREFIX/lib/mojo/asciichart/plot.mojo
      # Execute smoke test. In the build test environment the file lives under
      # info/recipe/, while in the installed test-files environment it is copied
      # next to this script. Handle both cases.
      - if [ -f info/recipe/test_package.mojo ]; then $PREFIX/bin/mojo -I $PREFIX/lib/mojo info/recipe/test_package.mojo; else $PREFIX/bin/mojo -I $PREFIX/lib/mojo test_package.mojo; fi

about:
  homepage: https://github.com/DataBooth/mojo-asciichart
  license: Apache-2.0
  license_file: LICENSE
  summary: Nice-looking lightweight console ASCII line charts for Mojo
  description: |
    mojo-asciichart is a native Mojo port of the popular asciichartpy Python library.
    Generate beautiful ASCII line charts in your terminal with no dependencies.

    Features:
    - Basic plot() function for single series
    - Configurable height and appearance
    - Automatic min/max detection and scaling
    - NaN value handling (gaps in data)
    - UTF-8 box-drawing characters for smooth curves
    - ANSI color support (6 predefined themes)
    - Python interop tests for compatibility validation
    - Pixel-perfect output matching asciichartpy
    - Performance: 1.4-4.3x faster than Python
    - Comprehensive test suite (29 tests passing)
  documentation: https://github.com/DataBooth/mojo-asciichart/blob/main/README.md
  repository: https://github.com/DataBooth/mojo-asciichart

extra:
  recipe-maintainers:
    - mjboothaus
